### ISSUE TITLE
State constraint

### ISSUE THREAD

**Issue by asmbrandao** [torrisig/FalcOpt#7]
Greetings,

I wonder if there is a straightforward way of applying simple (min, max) constraints to the states on FalcOpt.  The formulation presentend on the wiki has box constraints on controls only and i failed to figure out how to use the nonlinear constraint to implement state constraints, without having to explicitly write the prediction model on the constraint.

Best regards,
Adriano

**Comment by dafrick** [comment]
Hi Adriano,

Thanks for trying FalcOpt. As you can see from our [wiki](https://github.com/torrisig/FalcOpt/wiki), it is not possible to add state constraints for each state x_k. This is not even possible by using the nonlinear input constraint and the prediction model, e.g. n(f_k(u_0,...u_k)) <=, since that constraint depends on all inputs u from stage 0 up to k, whereas FalcOpt only supports constraints on u_k. Note that this is usually the case with gradient methods and is the price to pay for the additional speed that we achieve.

Now, there are limited ways in which state constraints can be introduced. Namely, you can have a single quadratic constraint on the final state. I realize that this is not documented (well) in the wiki and is also not particularly well in the Matlab help for FalcOpt. I will update this documentation in the next few days.

If you can be a bit more specific about what kinds of state constraints you need and why it may be possible for me to suggest a workaround.

Best,
Damian

**Comment by asmbrandao** [comment]
Thank's for the reply Damian.

I am exploring the avaliable MPC code generation tools (such as ACADO, CVXGEN, muAO-MPC, etc.) and the possibilities of each tool. For comparison purposes, i wanted to implement box constraints on the states over the prediction horizon, as the problem that i am using in the comparison has these operational restrictions, and now realize that it is not possible with FalcOpt.

It seems to me that CasADi is used in FalcOpt. If that's so, would it be possible to apply an saturation on the model as CasADi allows this kind of nonlinearity. 

On a side note, i am using FalcOpt directly in C (as suggested by my colleague @brunoml5) and found it to be very nice to use, so congratulations!

**Comment by dafrick** [comment]
We have two (simple) modes how you can generate gradients using the `'gradients'` option, the first is `'gradients', 'Matlab'`, where we use the Matlab code generation facilities and the second is `'gradients', 'casadi'`, where CasADi is used. In my experience the `'Matlab'` option provides slightly faster code.

You can try to use a saturating model, and I suspect that CasADi will be more likely to gracefully handle this kind of function, however, FalcOpt is a gradient-based method and saturation is inherently non-smooth, so there is no theoretical assurance that our algorithm will work in this case. Nevertheless, I would try and see what happens.

By the way: [FiOrdOs](http://fiordos.ethz.ch) is another gradient-based solver developed (many years ago) at our lab that you may want to check out.

We are always happy for people to use FalcOpt, so if you have any comments/suggestions on how to improve it please do not hesitate to let us know. You can also reach me by email: falcopt (at) damianfrick (dot) com
