### ISSUE TITLE
Control movements on objective function

### ISSUE THREAD

**Issue by asmbrandao** [torrisig/FalcOpt#8]
Greetings,

I am trying to use FalcOpt with a linear model to control a linear process (both models are equal). I intend the objective function of the controller to have a term for tracking the states and one term to minimize control movements. To do so, i created an augmented linear model (newA = [A,B;0,eye]; newB = [B;eye]) to have the control movements as manipulated variables and the original states plus the delayed controls as states of the augmented model. I've also put the terms realive to tracking of the new states that are controls to zero (so that the objective function has only the two terms i mentioned at the begining).

While simulating and performing a reference change on the states, FalcOpt is not able to track the references and exceeds the max number of iterations doing so. I've tried changing tolerances and increasing the maximum number of iterations with no success, so now i wonder if it is possible to use FalcOpt in such way.

Any ideas on why it's not working?

Best regards
Adriano

**Comment by torrisig** [comment]
Hi Adriano, sorry for the late reply. FalcOpt should be able to solve such a problem.

Some questions to better understand your issue:

1. What is the exit flag output by FalcOpt?
2. What did you set as variable_stepSize? 
3. Why not using the specific reference tracking option “trackReference”?

Giampaolo

**Comment by asmbrandao** [comment]
Thank's for the reply Giampaolo.

Answering your questions:

1. The exitflag is 0;
2. I tried setting it to true and false with not much change on the result;
3. I am using the trackReference option as i still need tracking on the states. One of my goals was to minimize the control movements, that's why i tred the augmented system described above.

Adriano.

**Comment by torrisig** [comment]
1) ok, then it means that it exceeds the max # of iterations
2) please try set variable_stepSize.active to false. Next try different
variable_stepSize.alpha_max  (e.g., 0.1, 0.5,, 1, 5, 10, ...) in order to
see if the convergence is too slow because of a slow step size. This can
have a big impact
3) As a second step, I would try to reformulate the problem without
augmenting it, because it seems to me that it is  unnecessarily increasing
the dimension of the problem. In fact, with track reference you can anyway
set a trade-off between state tracking and control usage (same Q and R
matrices). By the way, is the very first MPC instance that is not
converging or some later time step?

Thank you,
Giampaolo

2018-03-28 14:24 GMT+02:00 asmbrandao <notifications@github.com>:
